export const roomData = [
  {
    id: 7,
    img_path: "room18.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner18.jpg",
    exImg1: "extra2.jpg",
    exImg2: "extra1.jpg",
    exImg3: "extra3.jpg",
    price: 310,
  },
  {
    id: 6,
    img_path: "room19.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner19.jpg",
    exImg1: "extra6.jpg",
    exImg2: "extra5.jpg",
    exImg3: "extra4.jpg",
    price: 250,
  },
  {
    id: 5,
    img_path: "room20.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner20.jpg",
    exImg1: "extra5.jpg",
    exImg2: "extra1.jpg",
    exImg3: "extra6.jpg",
    price: 435,
  },
  {
    id: 4,
    img_path: "room21.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner21.jpg",
    exImg1: "extra5.jpg",
    exImg2: "extra4.jpg",
    exImg3: "extra1.jpg",
    price: 360,
  },
  {
    id: 3,
    img_path: "room22.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner22.jpg",
    exImg1: "extra1.jpg",
    exImg2: "extra3.jpg",
    exImg3: "extra5.jpg",
    price: 480,
  },
  {
    id: 2,
    img_path: "room23.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner23.jpg",
    exImg1: "extra2.jpg",
    exImg2: "extra6.jpg",
    exImg3: "extra1.jpg",
    price: 500,
  },
  {
    id: 1,
    img_path: "room24.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner24.jpg",
    exImg1: "extra1.jpg",
    exImg2: "extra6.jpg",
    exImg3: "extra2.jpg",
    price: 450,
  },
  {
    id: 24,
    img_path: "room1.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner1.jpg",
    exImg1: "extra3.jpg",
    exImg2: "extra2.jpg",
    exImg3: "extra1.jpg",
    price: 100,
  },
  {
    id: 23,
    img_path: "room2.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner2.jpg",
    exImg1: "extra4.jpg",
    exImg2: "extra5.jpg",
    exImg3: "extra6.jpg",
    price: 250,
  },
  {
    id: 22,
    img_path: "room3.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner3.jpg",
    exImg1: "extra5.jpg",
    exImg2: "extra1.jpg",
    exImg3: "extra3.jpg",
    price: 210,
  },
  {
    id: 21,
    img_path: "room4.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner4.jpg",
    exImg1: "extra2.jpg",
    exImg2: "extra4.jpg",
    exImg3: "extra6.jpg",
    price: 420,
  },
  {
    id: 20,
    img_path: "room5.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner5.jpg",
    exImg1: "extra3.jpg",
    exImg2: "extra1.jpg",
    exImg3: "extra6.jpg",
    price: 130,
  },
  {
    id: 19,
    img_path: "room6.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner6.jpg",
    exImg1: "extra4.jpg",
    exImg2: "extra3.jpg",
    exImg3: "extra1.jpg",
    price: 240,
  },
  {
    id: 18,
    img_path: "room7.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner7.jpg",
    exImg1: "extra5.jpg",
    exImg2: "extra3.jpg",
    exImg3: "extra1.jpg",
    price: 200,
  },
  {
    id: 17,
    img_path: "room8.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner8.jpg",
    exImg1: "extra6.jpg",
    exImg2: "extra1.jpg",
    exImg3: "extra2.jpg",
    price: 300,
  },
  {
    id: 16,
    img_path: "room9.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner9.jpg",
    exImg1: "extra2.jpg",
    exImg2: "extra4.jpg",
    exImg3: "extra6.jpg",
    price: 450,
  },
  {
    id: 15,
    img_path: "room10.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner10.jpg",
    exImg1: "extra5.jpg",
    exImg2: "extra6.jpg",
    exImg3: "extra1.jpg",
    price: 330,
  },
  {
    id: 14,
    img_path: "room11.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner11.jpg",
    exImg1: "extra3.jpg",
    exImg2: "extra1.jpg",
    exImg3: "extra6.jpg",
    price: 220,
  },
  {
    id: 13,
    img_path: "room12.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner12.jpg",
    exImg1: "extra4.jpg",
    exImg2: "extra2.jpg",
    exImg3: "extra5.jpg",
    price: 185,
  },
  {
    id: 12,
    img_path: "room13.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner13.jpg",
    exImg1: "extra6.jpg",
    exImg2: "extra4.jpg",
    exImg3: "extra1.jpg",
    price: 140,
  },
  {
    id: 11,
    img_path: "room14.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner14.jpg",
    exImg1: "extra2.jpg",
    exImg2: "extra4.jpg",
    exImg3: "extra1.jpg",
    price: 250,
  },
  {
    id: 10,
    img_path: "room15.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner15.jpg",
    exImg1: "extra1.jpg",
    exImg2: "extra6.jpg",
    exImg3: "extra2.jpg",
    price: 430,
  },
  {
    id: 9,
    img_path: "room16.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner16.jpg",
    exImg1: "extra3.jpg",
    exImg2: "extra6.jpg",
    exImg3: "extra1.jpg",
    price: 280,
  },
  {
    id: 8,
    img_path: "room17.jpg",
    type: "room type",
    desc: "room desc",
    bg: "banner17.jpg",
    exImg1: "extra2.jpg",
    exImg2: "extra5.jpg",
    exImg3: "extra6.jpg",
    price: 295,
  },
];
